index:
 path: /
 controller: App\Controller\DefaultController::index




category:
    path: /katalog-{id}
    controller: App\Controller\DefaultController::category


product:
   path: /product
   controller: App\Controller\ProductController::product